server:
  main:
    web-application-type: reactive
  port : 8766

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: orders
          uri: http://localhost:8080
          predicates:
            - Path=/orders/**