server:
  main:
    web-application-type: reactive
  port : 8765

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: inventorymanagement
          uri: http://localhost:8081
          predicates:
            - Path=/product/**